#!/bin/bash

echo "🔄 RESET SIMULATOR AND TEST ONBOARDING"
echo "======================================="

echo ""
echo "1. Resetting iOS Simulator..."
xcrun simctl erase all

echo ""
echo "2. Listing available simulators..."
xcrun simctl list devices | grep "iPhone"

echo ""
echo "3. Instructions for testing:"
echo "----------------------------"
echo "✅ Swift compilation error is FIXED"
echo "✅ All files are properly referenced in Xcode"
echo "✅ Video file exists and is referenced"
echo ""
echo "NEXT STEPS:"
echo "1. Open Xcode: open ios/App/App.xcodeproj"
echo "2. Clean build folder: Product → Clean Build Folder (Cmd+Shift+K)"
echo "3. Select iPhone simulator (iPhone 15 Pro recommended)"
echo "4. Build and run (Cmd+R)"
echo "5. Open Xcode Console: View → Debug Area → Activate Console"
echo ""
echo "EXPECTED BEHAVIOR:"
echo "- App should show onboarding video on first launch"
echo "- Debug indicator should show 'ONBOARDING' in top-right corner"
echo "- Console should show debug messages starting with 🎬"
echo "- Video should play automatically without skip option"
echo "- After video completes, should transition to login/signup"
echo ""
echo "DEBUG MESSAGES TO LOOK FOR:"
echo "🎬 ContentView init called"
echo "🎬 ContentView onAppear called"
echo "🎬 OnboardingManager initialized"
echo "🎬 Getting hasSeenOnboardingVideo: false"
echo "🎬 First launch detected, showing onboarding video"
echo "✅ Found video file: ivory - Made with Clipchamp.mov"
echo "🎬 Loading video from: ivory - Made with Clipchamp.mov"
echo "🎬 Starting video playback"
echo ""
echo "IF STILL NO VIDEO:"
echo "- Check if debug indicator shows 'ONBOARDING' or 'WEBVIEW'"
echo "- Look for any error messages in console"
echo "- Verify video file is actually in app bundle"
echo "- Try running: ./verify-bundle-contents.sh after building"